/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ModelClass.Usuario;
import Models.Cajas;
import Models.Usuarios;
import java.awt.Color;
import java.util.List;

/**
 *
 * @author AlexJPZ
 */
public class Login extends javax.swing.JFrame {

    Usuario usuario = new Usuario();

    public Login() {

        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        Label_Mensaje.setText("");
        TextField_Usuario.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Label_Usuario = new javax.swing.JLabel();
        TextField_Usuario = new javax.swing.JTextField();
        Label_Pass = new javax.swing.JLabel();
        PasswordField_Pass = new javax.swing.JPasswordField();
        Label_Mensaje = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Usuario.setText("Usuario");
        jPanel2.add(Label_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TextField_Usuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TextField_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_UsuarioKeyReleased(evt);
            }
        });
        jPanel2.add(TextField_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 35, 250, 35));

        Label_Pass.setText("Contraseña");
        jPanel2.add(Label_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        PasswordField_Pass.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PasswordField_Pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PasswordField_PassKeyReleased(evt);
            }
        });
        jPanel2.add(PasswordField_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 250, 33));

        Label_Mensaje.setForeground(new java.awt.Color(255, 51, 102));
        Label_Mensaje.setText("Mensaje");
        jPanel2.add(Label_Mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 59, 288, 170));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Iniciar sesión");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 268, 44));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setText("©PDHN");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_UsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_UsuarioKeyReleased
        if (TextField_Usuario.getText().equals("")) {
            Label_Usuario.setForeground(new Color(102, 102, 102));
        } else {
            Label_Usuario.setText("Usuario");
            Label_Usuario.setForeground(new Color(0, 153, 51));
        }
        Label_Mensaje.setText("");
    }//GEN-LAST:event_TextField_UsuarioKeyReleased

    private void PasswordField_PassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordField_PassKeyReleased
        String pass = new String(PasswordField_Pass.getPassword());
        if (pass.equals("")) {
            Label_Pass.setForeground(new Color(102, 102, 102));
        } else {
            Label_Pass.setText("Contraseña");
            Label_Pass.setForeground(new Color(0, 153, 51));
        }
        Label_Mensaje.setText("");
    }//GEN-LAST:event_PasswordField_PassKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        iniciarSesion();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void iniciarSesion() {
        if (TextField_Usuario.getText().equals("")) {
            Label_Usuario.setText("Ingrese el usuario");
            Label_Usuario.setForeground(Color.RED);
            TextField_Usuario.requestFocus();
        } else {
            String pass = new String(PasswordField_Pass.getPassword());
            if (pass.equals("")) {
                Label_Pass.setText("Ingrese la contraseña");
                Label_Pass.setForeground(Color.RED);
                PasswordField_Pass.requestFocus();
            } else {
                Object[] objects = usuario.login(TextField_Usuario.getText(), pass);
                List<Usuarios> listUsuario = (List<Usuarios>) objects[0];
                List<Cajas> listCaja = (List<Cajas>) objects[1];
                if (0 < listUsuario.size()) {
                    if (listUsuario.get(0).getRole().equals("Admin")) {
                        Sistema sisten = new Sistema(listUsuario, listCaja);
                        sisten.setVisible(true);
                        sisten.setExtendedState(MAXIMIZED_BOTH);
                        this.setVisible(false);
                    } else {
                        if (0 < listCaja.size()) {
                            Sistema sisten = new Sistema(listUsuario, listCaja);
                            sisten.setVisible(true);
                            sisten.setExtendedState(MAXIMIZED_BOTH);
                            this.setVisible(false);
                        } else {
                            Label_Mensaje.setText("No hay cajas disponibles");
                        }
                    }
                } else {
                    Label_Mensaje.setText("Usuario o Contraseña incorrecta");
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Mensaje;
    private javax.swing.JLabel Label_Pass;
    private javax.swing.JLabel Label_Usuario;
    private javax.swing.JPasswordField PasswordField_Pass;
    private javax.swing.JTextField TextField_Usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
